language: python

python:
  - "2.7"

install:
  - python setup.py install

script:
  - python tests/test.py

notifications:
  email:
    recipients:
      - krzysztof.bandurski@gmail.com
    on_success: change
    on_failure: change
